"""Inicializar base de datos

Revision ID: 67c865a88aef
Revises: da35d9252ba7
Create Date: 2025-09-29 09:31:47.586541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '67c865a88aef'
down_revision: Union[str, Sequence[str], None] = 'da35d9252ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
