"""Agregar nuevas tablas

Revision ID: c1febbbe8020
Revises: 67c865a88aef
Create Date: 2025-10-17 10:46:31.191891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1febbbe8020'
down_revision: Union[str, Sequence[str], None] = '67c865a88aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cables', 'estado',
               existing_type=postgresql.ENUM('NUEVO', 'USADO', 'DANADO', name='estadocableenum'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('discos_duros', 'tipo',
               existing_type=postgresql.ENUM('SSD', 'HDD', 'OTRO', name='tipodiscoenum'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('evidencias', 'url_imagen',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('evidencias', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('evidencias', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('gps_modelos', 'modelo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('gps_modelos', 'nodeos',
               existing_type=postgresql.ENUM('FMDC', 'FMU', 'FMC003', name='nodeosenum'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('gps_modelos', 'tipo_telefonia',
               existing_type=postgresql.ENUM('GSM', 'CDMA', 'LTE', name='tipotelefoniaenum'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('inventario_interno', 'unidad_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventario_interno', 'pieza_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventario_interno', 'cantidad',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventario_interno', 'danado',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('lectoras', 'tipo',
               existing_type=postgresql.ENUM('CODIGO', 'BARRAS', 'RFID', name='tipolectoraenum'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('log_fallas', 'unidad_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('log_fallas', 'falla_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('log_fallas', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('log_fallas', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('log_fallas', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('log_fallas_falla_id_fkey'), 'log_fallas', type_='foreignkey')
    op.drop_constraint(op.f('log_fallas_unidad_id_fkey'), 'log_fallas', type_='foreignkey')
    op.create_foreign_key(None, 'log_fallas', 'fallas', ['falla_id'], ['id'])
    op.create_foreign_key(None, 'log_fallas', 'unidades', ['unidad_id'], ['id'])
    op.alter_column('piezas', 'tipo',
               existing_type=postgresql.ENUM('LECTORA', 'DISCO_DURO', 'CABLE', 'GPS', 'CAMARA', name='tipopiezaenum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('piezas', 'id_opcion',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('piezas', 'nombre',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('piezas', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servicio_evidencia', 'tipo',
               existing_type=postgresql.ENUM('ANTES', 'DESPUES', 'PROCESO', name='tipoevidenciaenum'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('servicio_extension', 'servicio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servicio_extension', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servicio_extension', 'duracion',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('servicio_extension', 'fecha_solicitud',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('servicio_extension', 'aprobado',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('servicio_extension_usuario_id_fkey'), 'servicio_extension', type_='foreignkey')
    op.drop_constraint(op.f('servicio_extension_servicio_id_fkey'), 'servicio_extension', type_='foreignkey')
    op.create_foreign_key(None, 'servicio_extension', 'servicios', ['servicio_id'], ['id'])
    op.create_foreign_key(None, 'servicio_extension', 'usuarios', ['usuario_id'], ['id'])
    op.alter_column('servicio_pendiente', 'servicio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servicio_pendiente', 'usuario_id_admin',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servicio_pendiente', 'tecnico_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servicio_pendiente', 'estado',
               existing_type=postgresql.ENUM('PENDIENTE', 'EN_PROCESO', 'FINALIZADO', name='estadopendienteenum'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('servicio_pendiente', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('servicio_pendiente_usuario_id_admin_fkey'), 'servicio_pendiente', type_='foreignkey')
    op.drop_constraint(op.f('servicio_pendiente_tecnico_id_fkey'), 'servicio_pendiente', type_='foreignkey')
    op.create_foreign_key(None, 'servicio_pendiente', 'usuarios', ['tecnico_id'], ['id'])
    op.create_foreign_key(None, 'servicio_pendiente', 'usuarios', ['usuario_id_admin'], ['id'])
    op.alter_column('servicio_pieza', 'cantidad',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('servicio_pieza_pieza_id_fkey'), 'servicio_pieza', type_='foreignkey')
    op.create_foreign_key(None, 'servicio_pieza', 'piezas', ['pieza_id'], ['id'])
    op.alter_column('servicio_tiempo', 'servicio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servicio_tiempo', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servicio_tiempo', 'accion',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('servicio_tiempo', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('servicio_tiempo_usuario_id_fkey'), 'servicio_tiempo', type_='foreignkey')
    op.drop_constraint(op.f('servicio_tiempo_servicio_id_fkey'), 'servicio_tiempo', type_='foreignkey')
    op.create_foreign_key(None, 'servicio_tiempo', 'servicios', ['servicio_id'], ['id'])
    op.create_foreign_key(None, 'servicio_tiempo', 'usuarios', ['usuario_id'], ['id'])
    op.alter_column('unidad_pieza_registro', 'unidad_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('unidad_pieza_registro', 'inventario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('unidad_pieza_registro', 'cantbus',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('unidad_pieza_registro', 'danado',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('unidad_pieza_registro', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unidad_pieza_registro', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('unidad_pieza_registro', 'danado',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('unidad_pieza_registro', 'cantbus',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('unidad_pieza_registro', 'inventario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('unidad_pieza_registro', 'unidad_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'servicio_tiempo', type_='foreignkey')
    op.drop_constraint(None, 'servicio_tiempo', type_='foreignkey')
    op.create_foreign_key(op.f('servicio_tiempo_servicio_id_fkey'), 'servicio_tiempo', 'servicios', ['servicio_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('servicio_tiempo_usuario_id_fkey'), 'servicio_tiempo', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.alter_column('servicio_tiempo', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('servicio_tiempo', 'accion',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('servicio_tiempo', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('servicio_tiempo', 'servicio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'servicio_pieza', type_='foreignkey')
    op.create_foreign_key(op.f('servicio_pieza_pieza_id_fkey'), 'servicio_pieza', 'piezas', ['pieza_id'], ['id'], ondelete='CASCADE')
    op.alter_column('servicio_pieza', 'cantidad',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'servicio_pendiente', type_='foreignkey')
    op.drop_constraint(None, 'servicio_pendiente', type_='foreignkey')
    op.create_foreign_key(op.f('servicio_pendiente_tecnico_id_fkey'), 'servicio_pendiente', 'usuarios', ['tecnico_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('servicio_pendiente_usuario_id_admin_fkey'), 'servicio_pendiente', 'usuarios', ['usuario_id_admin'], ['id'], ondelete='CASCADE')
    op.alter_column('servicio_pendiente', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('servicio_pendiente', 'estado',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('PENDIENTE', 'EN_PROCESO', 'FINALIZADO', name='estadopendienteenum'),
               nullable=False)
    op.alter_column('servicio_pendiente', 'tecnico_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('servicio_pendiente', 'usuario_id_admin',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('servicio_pendiente', 'servicio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'servicio_extension', type_='foreignkey')
    op.drop_constraint(None, 'servicio_extension', type_='foreignkey')
    op.create_foreign_key(op.f('servicio_extension_servicio_id_fkey'), 'servicio_extension', 'servicios', ['servicio_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('servicio_extension_usuario_id_fkey'), 'servicio_extension', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.alter_column('servicio_extension', 'aprobado',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('servicio_extension', 'fecha_solicitud',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('servicio_extension', 'duracion',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('servicio_extension', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('servicio_extension', 'servicio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('servicio_evidencia', 'tipo',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('ANTES', 'DESPUES', 'PROCESO', name='tipoevidenciaenum'),
               nullable=False)
    op.alter_column('piezas', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('piezas', 'nombre',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('piezas', 'id_opcion',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('piezas', 'tipo',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('LECTORA', 'DISCO_DURO', 'CABLE', 'GPS', 'CAMARA', name='tipopiezaenum'),
               existing_nullable=False)
    op.drop_constraint(None, 'log_fallas', type_='foreignkey')
    op.drop_constraint(None, 'log_fallas', type_='foreignkey')
    op.create_foreign_key(op.f('log_fallas_unidad_id_fkey'), 'log_fallas', 'unidades', ['unidad_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('log_fallas_falla_id_fkey'), 'log_fallas', 'fallas', ['falla_id'], ['id'], ondelete='CASCADE')
    op.alter_column('log_fallas', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('log_fallas', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('log_fallas', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('log_fallas', 'falla_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('log_fallas', 'unidad_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lectoras', 'tipo',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('CODIGO', 'BARRAS', 'RFID', name='tipolectoraenum'),
               nullable=False)
    op.alter_column('inventario_interno', 'danado',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('inventario_interno', 'cantidad',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventario_interno', 'pieza_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventario_interno', 'unidad_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('gps_modelos', 'tipo_telefonia',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('GSM', 'CDMA', 'LTE', name='tipotelefoniaenum'),
               nullable=False)
    op.alter_column('gps_modelos', 'nodeos',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('FMDC', 'FMU', 'FMC003', name='nodeosenum'),
               nullable=False)
    op.alter_column('gps_modelos', 'modelo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('evidencias', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('evidencias', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('evidencias', 'url_imagen',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('discos_duros', 'tipo',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('SSD', 'HDD', 'OTRO', name='tipodiscoenum'),
               nullable=False)
    op.alter_column('cables', 'estado',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('NUEVO', 'USADO', 'DANADO', name='estadocableenum'),
               nullable=False)
    # ### end Alembic commands ###
