"""Inicializar base de datos

Revision ID: da35d9252ba7
Revises: 293a66d03e32
Create Date: 2025-09-29 09:26:52.026606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da35d9252ba7'
down_revision: Union[str, Sequence[str], None] = '293a66d03e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('unidad_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'unidades', ['unidad_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'unidad_id')
    # ### end Alembic commands ###
