"""Agregar tabla Planta y planta_id en Unidad

Revision ID: e5bc77b1279c
Revises: 06680d6d62d1
Create Date: 2025-10-20 10:05:47.516204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5bc77b1279c'
down_revision: Union[str, Sequence[str], None] = '06680d6d62d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantas_id'), 'plantas', ['id'], unique=False)
    op.add_column('unidades', sa.Column('planta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'unidades', 'plantas', ['planta_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unidades', type_='foreignkey')
    op.drop_column('unidades', 'planta_id')
    op.drop_index(op.f('ix_plantas_id'), table_name='plantas')
    op.drop_table('plantas')
    # ### end Alembic commands ###
